### ISSUE TITLE
unexpected crash

### ISSUE THREAD

**Issue by tigercosmos** [trou/cpu_rec_rs#1]
Crashed when run `./cpu_rec_rs  /bin/bash`

- Debian 11
- rustc 1.70.0

```log
$ RUST_BACKTRACE=1 ./cpu_rec_rs  /bin/bash
Loading corpus from cpu_rec_corpus/*.corpus
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:91:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:162:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/index.rs:19:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/mod.rs:2691:9
   6: cpu_rec_rs::predict
             at /home/cpu_rec_rs/src/main.rs:91:26
   7: cpu_rec_rs::guess_with_windows
             at /home/cpu_rec_rs/src/main.rs:109:20
   8: cpu_rec_rs::main
             at /home/cpu_rec_rs/src/main.rs:243:18
   9: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by trou** [comment]
Indeed this is a very unhelpful way of bailing out when the corpus_directory is not found. I'll make it clearer soon.

**Comment by trou** [comment]
Fixed. Thanks for the report.
